pub mod arrow;
pub mod diamond;
pub mod doublebox;
pub mod ellipse;
pub mod freehand;
pub mod line;
pub mod rectangle;
pub mod select;
pub mod text;

pub use arrow::handle_arrow_event;
pub use diamond::handle_diamond_event;
pub use doublebox::handle_doublebox_event;
pub use ellipse::handle_ellipse_event;
pub use freehand::handle_freehand_event;
pub use line::handle_line_event;
pub use rectangle::handle_rectangle_event;
pub use select::handle_select_event;
pub use text::handle_text_event;
